GatewayID GW-D00B-40C7
ExternalInterface eth0.1
GatewayInterface br-lan

AuthServer {
    Hostname 16.16.159.119
    HTTPPort 3000
    SSLAvailable no
    Path /api/wifidog/
}

GatewayPort 2060
HTTPDMaxConn 253
ClientTimeout 10
CheckInterval 60
PopularServers kernel.org,ieee.org

FirewallRuleSet global {
    FirewallRule allow to 16.16.159.119
}

FirewallRuleSet validating-users {
    FirewallRule allow to 0.0.0.0/0
}

FirewallRuleSet known-users {
    FirewallRule allow to 0.0.0.0/0
}

FirewallRuleSet unknown-users {
    FirewallRule allow tcp to 16.16.159.119
    FirewallRule block udp port 53
    FirewallRule block tcp port 53
    FirewallRule block udp port 67
    FirewallRule block tcp port 67
}

FirewallRuleSet locked-users {
    FirewallRule block to 0.0.0.0/0
}
